# Generated by Django 2.1.1 on 2018-09-18 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_ts', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 20, 22, 50, 328147))),
                ('data', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
