export const views = {
    MAIN_PAGE: "MAIN_PAGE",
    LOGIN_PAGE: "LOGIN_PAGE",
    REGISTRATION_PAGE: "REGISTRATION_PAGE",
    CHAMPIONSHIPS_PAGE: " CHAMPIONSHIPS_PAGE",
    RATING_PAGE: "RATING_PAGE",
    ABOUT_PAGE: "ABOUT_PAGE",
};